### ISSUE TITLE
Revamp package list

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/juliadiff.github.io#24]
The list of packages on https://juliadiff.org/ is pretty outdated, and the ones on top are not necessarily the most widely used or actively maintained.

@oxinabox @ChrisRackauckas I can do a PR to reorder / delete names but I'd need help to figure things out. What do you suggest looking at? GitHub activity? Package stats?

**Comment by gdalle** [comment]
also pinging @adrhill

**Comment by ChrisRackauckas** [comment]
https://juliahub.com/ui/Search?q=JuliaDiff&type=packages gives monthly downloads. But it's the ones you would expect:

1. ChainRules(Core)
2. ForwardDiff
3. FiniteDiff
4. SparseDiffTools
5. ReverseDiff

Those are the ones to highlight, and then... there's everything else like FiniteDifferences.jl, PolyesterForwardDiff.jl, DualNumbers.jl (Should we even mention that one? Because it really shouldn't be used...), TaylorDiff.jl,

**Comment by oxinabox** [comment]
I think its worth including basically everything, but just like making it fairly clear that e.g. `DualNumber.jl` is primarily interesting as a pedological example.

I think its nice to be comprehensive, and to include old stuff that people might have heard about but maybe shouldn't use today.
